In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [2]:
# 브라우저 열기
driver = webdriver.Chrome()

# 페이지 접속하기
url = 'https://kovo.co.kr/KOVO/game/v-league?first=%ED%8C%80+%EC%88%9C%EC%9C%84'
driver.get(url)

# 명시적 대기 설정 (최대 10초 대기)
wait = WebDriverWait(driver, 10)

# 여자부 클릭하기 (클릭이 가능할 때까지 대기)
try:
    # 요소가 클릭 가능한 상태일 때까지 대기
    click_1 = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "label:nth-child(2)")))
    click_1.click()
    time.sleep(1)
except Exception as e:
    print("오류 발생:", e)

In [3]:
# 시즌 클릭하기
click_2 = driver.find_elements(By.CSS_SELECTOR,"span.ant-select-selection-item")
click_2[0].click()
time.sleep(1)

# ActionChains 객체 생성
actions = ActionChains(driver)

# 방향키 입력 (예: 아래 방향키)
actions.send_keys(Keys.ARROW_DOWN).perform()
time.sleep(1)

# 엔터키 입력
actions.send_keys(Keys.ENTER).perform()
time.sleep(1)

In [4]:
for num in range(2):
    # 시즌 클릭하기
    click_2 = driver.find_elements(By.CSS_SELECTOR,"span.ant-select-selection-item")
    click_2[0].click()
    time.sleep(1)
    
    # ActionChains 객체 생성
    actions = ActionChains(driver)
    
    # 방향키 입력 (예: 아래 방향키)
    actions.send_keys(Keys.ARROW_DOWN).perform()
    time.sleep(1)
    
    # 엔터키 입력
    actions.send_keys(Keys.ENTER).perform()
    time.sleep(1)

    for numm in range(7):
        # 라운드 클릭하기
        click_2 = driver.find_elements(By.CSS_SELECTOR,"span.ant-select-selection-item")
        click_2[2].click()
        time.sleep(1)
        
        # ActionChains 객체 생성
        actions = ActionChains(driver)
        
        # 방향키 입력 (예: 아래 방향키)
        actions.send_keys(Keys.ARROW_DOWN).perform()
        time.sleep(1)
        
        # 엔터키 입력
        actions.send_keys(Keys.ENTER).perform()
        time.sleep(1)
         
        
        click_3 = driver.find_elements(By.CSS_SELECTOR, "button.font-normal")
        c_num = [1, 8, 9]
        
        for numb in range(3):
            for j in c_num:
                click_3[j].click()
                time.sleep(1)
                
                # HTML 다운 받기 & 해석하기
                soup = BeautifulSoup(driver.page_source, 'lxml')
                time.sleep(1)
                
                # 셀 데이터 크롤링
                stat_list = soup.select("tr > td")
                
                stats = []
                for item in stat_list:
                    stat = item.text
                    data = [stat]
                    stats.append(data)
            
                # ".\xa0"값 제거
                cleaned_stats = [item for item in stats if item != ['\xa0']]
            
                # 리스트를 하나로 합치기
                flattened_list = [item for sublist in cleaned_stats for item in sublist]
                list = flattened_list[84:]
            
                # 리스트를 NumPy 배열로 변환
                np_array = np.array(list)
                
                # reshape 사용
                reshaped_array = np_array.reshape(7, -1)
            
                # 데이터프레임으로 전환
                df = pd.DataFrame(reshaped_array)
            
                # globals()를 사용하여 df1, df8, df9와 같은 변수명을 동적으로 생성
                globals()[f"df{j}"] = df
            
            df1.columns = ["공격_순위", "팀", "경기수", "세트수", "공격_시도", "공격_성공", "공격차단", "공격_범실", "공격_성공률"]
            df8.columns =["서브_순위", "팀", "경기수", "세트수", "서브_시도", "서브_성공", "서브_범실", "서브_세트당평균"]
            df9.columns = ["블로킹_순위", "팀", "경기수", "세트수", "블로킹_시도", "블로킹_성공", "블로킹_유효블락", "블로킹_실패", "블로킹_범실", "블로킹_어시스트", "블로킹_세트당평균"]
            df8 = df8.drop(["경기수", "세트수"], axis = 1)
            df9 = df9.drop(["경기수", "세트수"], axis = 1)
            # df1, df8, df9가 이미 "팀" 기준으로 합쳐질 준비가 되어 있으므로, 각 데이터프레임에서 "팀" 열을 기준으로 병합합니다.
            
            # df1과 df8을 팀 기준으로 병합
            merged_df_1_8 = pd.merge(df1, df8, on="팀", how="outer")
            
            # 그 결과와 df9를 팀 기준으로 병합
            season_df = pd.merge(merged_df_1_8, df9, on="팀", how="outer")
            
            # globals()를 사용하여 season_df0, season_df1, season_df2와 같은 변수명을 동적으로 생성
            globals()[f"round_df{num}{numm}"] = season_df

In [5]:
for num in range(4):
    # 시즌 클릭하기
    click_2 = driver.find_elements(By.CSS_SELECTOR,"span.ant-select-selection-item")
    click_2[0].click()
    time.sleep(1)
    
    # ActionChains 객체 생성
    actions = ActionChains(driver)
    
    # 방향키 입력 (예: 아래 방향키)
    actions.send_keys(Keys.ARROW_DOWN).perform()
    time.sleep(1)
    
    # 엔터키 입력
    actions.send_keys(Keys.ENTER).perform()
    time.sleep(1)

    for numm in range(7):
        # 라운드 클릭하기
        click_2 = driver.find_elements(By.CSS_SELECTOR,"span.ant-select-selection-item")
        click_2[2].click()
        time.sleep(1)
        
        # ActionChains 객체 생성
        actions = ActionChains(driver)
        
        # 방향키 입력 (예: 아래 방향키)
        actions.send_keys(Keys.ARROW_DOWN).perform()
        time.sleep(1)
        
        # 엔터키 입력
        actions.send_keys(Keys.ENTER).perform()
        time.sleep(1)
         
        
        click_3 = driver.find_elements(By.CSS_SELECTOR, "button.font-normal")
        c_num = [1, 8, 9]
        
        for numb in range(3):
            for j in c_num:
                click_3[j].click()
                time.sleep(1)
                
                # HTML 다운 받기 & 해석하기
                soup = BeautifulSoup(driver.page_source, 'lxml')
                time.sleep(1)
                
                # 셀 데이터 크롤링
                stat_list = soup.select("tr > td")
                
                stats = []
                for item in stat_list:
                    stat = item.text
                    data = [stat]
                    stats.append(data)
            
                # ".\xa0"값 제거
                cleaned_stats = [item for item in stats if item != ['\xa0']]
            
                # 리스트를 하나로 합치기
                flattened_list = [item for sublist in cleaned_stats for item in sublist]
                list = flattened_list[72:]
            
                # 리스트를 NumPy 배열로 변환
                np_array = np.array(list)
                
                # reshape 사용
                reshaped_array = np_array.reshape(6, -1)
            
                # 데이터프레임으로 전환
                df = pd.DataFrame(reshaped_array)
            
                # globals()를 사용하여 df1, df8, df9와 같은 변수명을 동적으로 생성
                globals()[f"df{j}"] = df
            
            df1.columns = ["공격_순위", "팀", "경기수", "세트수", "공격_시도", "공격_성공", "공격차단", "공격_범실", "공격_성공률"]
            df8.columns =["서브_순위", "팀", "경기수", "세트수", "서브_시도", "서브_성공", "서브_범실", "서브_세트당평균"]
            df9.columns = ["블로킹_순위", "팀", "경기수", "세트수", "블로킹_시도", "블로킹_성공", "블로킹_유효블락", "블로킹_실패", "블로킹_범실", "블로킹_어시스트", "블로킹_세트당평균"]
            df8 = df8.drop(["경기수", "세트수"], axis = 1)
            df9 = df9.drop(["경기수", "세트수"], axis = 1)
            # df1, df8, df9가 이미 "팀" 기준으로 합쳐질 준비가 되어 있으므로, 각 데이터프레임에서 "팀" 열을 기준으로 병합합니다.
            
            # df1과 df8을 팀 기준으로 병합
            merged_df_1_8 = pd.merge(df1, df8, on="팀", how="outer")
            
            # 그 결과와 df9를 팀 기준으로 병합
            season_df = pd.merge(merged_df_1_8, df9, on="팀", how="outer")
            
            # globals()를 사용하여 season_df0, season_df1, season_df2와 같은 변수명을 동적으로 생성
            globals()[f"round_df{num + 2}{numm}"] = season_df

In [6]:
# 시즌 컬럼 생성
for i in range(0, 56):  
    df_name = f"round_df{i:02d}"  
    
    if i // 10 == 0:
        season = "22-23"
    elif i // 10 == 1:
        season = "21-22"
    elif i // 10 == 2:
        season = "20-21"
    elif i // 10 == 3:
        season = "19-20"
    elif i // 10 == 4:
        season = "18-19"
    elif i // 10 == 5:
        season = "17-18"
    
    # 변수 존재 여부 확인 후 "시즌" 컬럼 추가
    if df_name in globals():
        globals()[df_name]["시즌"] = season
    else:
        pass

In [7]:
# 라운드 컬럼 생성
for i in range(0, 56):  
    df_name = f"round_df{i:02d}"  
    
    if i % 10 == 0:
        round = 1
    elif i % 10 == 1:
        round = 2
    elif i % 10 == 2:
        round = 3
    elif i % 10 == 3:
        round = 4
    elif i % 10 == 4:
        round = 5
    elif i % 10 == 5:
        round = 6
    
    # 변수 존재 여부 확인 후 "라운드" 컬럼 추가
    if df_name in globals():
        globals()[df_name]["라운드"] = round
    else:
        pass

In [8]:
# 빈 리스트 생성
dfs = []

# 00부터 55까지 반복
for i in range(0, 56):
    # 제외할 번호 리스트
    if i % 10 in [6]:  # 06, 16, 26, 36, 46, 56 제외
        continue
    
    # 데이터프레임 이름 생성
    df_name = f"round_df{i:02d}"  # "round_df00", "round_df01", ..., "round_df55" 형식으로 생성
    
    # 해당 변수 이름이 globals()에 있는지 확인
    if df_name in globals():
        dfs.append(globals()[df_name])  # 해당 데이터프레임을 리스트에 추가

# 데이터프레임들을 세로로 합치기
round_df = pd.concat(dfs, axis=0, ignore_index=True)

In [9]:
df_loaded = pd.read_csv('23-24시즌 라운드별 데이터.csv')

In [10]:
round_df = pd.concat([round_df, df_loaded], axis=0, ignore_index=True)

In [11]:
round_df

,공격_순위,팀,경기수,세트수,공격_시도,공격_성공,공격차단,공격_범실,공격_성공률,서브_순위,...,블로킹_순위,블로킹_시도,블로킹_성공,블로킹_유효블락,블로킹_실패,블로킹_범실,블로킹_어시스트,블로킹_세트당평균,시즌,라운드
0,4,GS칼텍스,6,21,678,273,48,39,40.27,6,...,6,314,39,108,111,4,37,1.86,22-23,1
1,6,IBK기업은행,6,23,892,301,55,65,33.74,3,...,5,405,46,175,113,4,38,2,22-23,1
2,3,KGC인삼공사,6,25,825,338,60,65,40.97,4,...,3,423,54,162,121,8,45,2.16,22-23,1
3,7,페퍼저축은행,6,23,794,263,53,49,33.12,7,...,7,381,38,148,122,7,28,1.65,22-23,1
4,5,한국도로공사,6,24,824,319,41,47,38.71,5,...,2,378,53,125,129,9,44,2.21,22-23,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,4,정관장,6,23,841,339,42,42,40.31,5,...,3,400,50,156,126,4,36,2.17,23-24,6
266,5,페퍼저축은행,6,25,896,358,52,51,39.96,6,...,5,458,53,191,145,8,47,2.12,23-24,6
267,1,한국도로공사,6,26,909,377,51,67,41.47,7,...,6,433,45,162,146,7,40,1.73,23-24,6
268,2,현대건설,6,23,766,314,43,35,40.99,4,...,1,394,57,147,137,2,44,2.48,23-24,6
269,3,흥국생명,6,22,852,345,39,52,40.49,2,...,4,423,47,186,122,10,35,2.14,23-24,6

In [12]:
round_df['팀'] = round_df['팀'].replace('KGC인삼공사', '정관장') # 바뀌었던 팀명 통일

In [13]:
round_df.insert(0, '라운드', round_df.pop('라운드'))
round_df.insert(0, '시즌', round_df.pop('시즌'))

In [14]:
round_df

,시즌,라운드,공격_순위,팀,경기수,세트수,공격_시도,공격_성공,공격차단,공격_범실,...,서브_범실,서브_세트당평균,블로킹_순위,블로킹_시도,블로킹_성공,블로킹_유효블락,블로킹_실패,블로킹_범실,블로킹_어시스트,블로킹_세트당평균
0,22-23,1,4,GS칼텍스,6,21,678,273,48,39,...,46,0.67,6,314,39,108,111,4,37,1.86
1,22-23,1,6,IBK기업은행,6,23,892,301,55,65,...,59,1.04,5,405,46,175,113,4,38,2
2,22-23,1,3,정관장,6,25,825,338,60,65,...,62,0.84,3,423,54,162,121,8,45,2.16
3,22-23,1,7,페퍼저축은행,6,23,794,263,53,49,...,38,0.65,7,381,38,148,122,7,28,1.65
4,22-23,1,5,한국도로공사,6,24,824,319,41,47,...,49,0.75,2,378,53,125,129,9,44,2.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,23-24,6,4,정관장,6,23,841,339,42,42,...,39,0.91,3,400,50,156,126,4,36,2.17
266,23-24,6,5,페퍼저축은행,6,25,896,358,52,51,...,38,0.84,5,458,53,191,145,8,47,2.12
267,23-24,6,1,한국도로공사,6,26,909,377,51,67,...,51,0.77,6,433,45,162,146,7,40,1.73
268,23-24,6,2,현대건설,6,23,766,314,43,35,...,37,1.13,1,394,57,147,137,2,44,2.48
269,23-24,6,3,흥국생명,6,22,852,345,39,52,...,37,1.18,4,423,47,186,122,10,35,2.14

In [16]:
round_df_final = round_df.sort_values(by=['시즌', '라운드'])

In [17]:
round_df_final

,시즌,라운드,공격_순위,팀,경기수,세트수,공격_시도,공격_성공,공격차단,공격_범실,...,서브_범실,서브_세트당평균,블로킹_순위,블로킹_시도,블로킹_성공,블로킹_유효블락,블로킹_실패,블로킹_범실,블로킹_어시스트,블로킹_세트당평균
192,17-18,1,1,GS칼텍스,30,117,4208,1670,257,269,...,236,1.21,5,1846,213,678,564,31,163,1.82
193,17-18,1,3,IBK기업은행,30,116,4156,1612,248,233,...,240,1.28,3,1938,251,809,500,30,192,2.16
194,17-18,1,5,정관장,30,114,4233,1459,272,282,...,175,0.89,4,1882,244,716,578,24,190,2.14
195,17-18,1,2,한국도로공사,30,120,4308,1679,250,198,...,284,1.19,2,1921,268,712,569,43,219,2.23
196,17-18,1,4,현대건설,30,116,4123,1570,210,257,...,177,1.26,1,2065,336,658,645,42,267,2.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,23-24,6,4,정관장,6,23,841,339,42,42,...,39,0.91,3,400,50,156,126,4,36,2.17
266,23-24,6,5,페퍼저축은행,6,25,896,358,52,51,...,38,0.84,5,458,53,191,145,8,47,2.12
267,23-24,6,1,한국도로공사,6,26,909,377,51,67,...,51,0.77,6,433,45,162,146,7,40,1.73
268,23-24,6,2,현대건설,6,23,766,314,43,35,...,37,1.13,1,394,57,147,137,2,44,2.48
269,23-24,6,3,흥국생명,6,22,852,345,39,52,...,37,1.18,4,423,47,186,122,10,35,2.14